pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-p 9090:9090'
        }
    }
    environment {
        CI = 'true'
        NODE_ENV = 'development'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}